config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :game_sessions
  resources :players
  resources :pages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/game_session.rb
class GameSession < ApplicationRecord
  has_many :player_game_sessions
  has_many :players, through: :player_game_sessions

  accepts_nested_attributes_for :players, reject_if: :all_blank, allow_destroy: true
  has_one :game
  has_one :winner, through: :players
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :player_game_sessions
  has_many :game_sessions, through: :player_game_sessions
end

app/models/player_game_session.rb
class PlayerGameSession < ApplicationRecord
  belongs_to :game_session
  belongs_to :player
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController
  before_action :set_game_session, only: %i[ show edit update destroy ]

  # GET /game_sessions
  def index
    @game_sessions = GameSession.all
  end

  # GET /game_sessions/1
  def show
  end

  # GET /game_sessions/new
  def new
    @game_session = GameSession.new
  end

  # GET /game_sessions/1/edit
  def edit
  end

  # POST /game_sessions
  def create
    @game_session = GameSession.new(game_session_params)

    if @game_session.save
      redirect_to @game_session, notice: "Game session was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /game_sessions/1
  def update
    if @game_session.update(game_session_params)
      redirect_to @game_session, notice: "Game session was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /game_sessions/1
  def destroy
    @game_session.destroy
    redirect_to game_sessions_url, notice: "Game session was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_session
      @game_session = GameSession.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_session_params
      params.require(:game_session).permit(:game, :winner_id, player_game_sessions: [:id, :_destroy, :points])
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to @game, notice: "Game was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      redirect_to @game, notice: "Game was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    redirect_to games_url, notice: "Game was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /pages
  def index
    @pages = Page.all
  end

  # GET /pages/1
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to @page, notice: "Page was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /pages/1
  def update
    if @page.update(page_params)
      redirect_to @page, notice: "Page was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /pages/1
  def destroy
    @page.destroy
    redirect_to pages_url, notice: "Page was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:title)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players
  def index
    @players = Player.all
  end

  # GET /players/1
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to @player, notice: "Player was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /players/1
  def update
    if @player.update(player_params)
      redirect_to @player, notice: "Player was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /players/1
  def destroy
    @player.destroy
    redirect_to players_url, notice: "Player was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_sessions_helper.rb
module GameSessionsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/game_sessions/_form.html.haml
= form_for @game_session do |f|
  - if @game_session.errors.any?
    =render 'shared/errors', object: @game_session

  = f.label :game
  = f.select :game, Game.all.collect {|p| [p.name, p.id]}

  = f.label :winner
  = f.select :winner_id, Player.all.collect {|p| [p.name, p.id]}

  %h3 Players
  #players
    =f.fields_for :players do |player|
      = render 'player_fields', f: player
    .links
      = link_to_add_association 'add player', f, :players, class: "btn btn-success"

  = f.submit

app/views/game_sessions/_game_session.html.erb
<div id="<%= dom_id game_session %>">
  <p>
    <strong>Game:</strong>
    <%= game_session.game %>
  </p>

  <p>
    <strong>Winner:</strong>
    <%= game_session.winner_id %>
  </p>

</div>

app/views/game_sessions/_player_fields.html.haml
.nested-fields
  = f.select :name, Player.all
  %h3 Hello world!

app/views/game_sessions/edit.html.erb
<h1>Editing game session</h1>

<%= render "form", game_session: @game_session %>

<br>

<div>
  <%= link_to "Show this game session", @game_session %> |
  <%= link_to "Back to game sessions", game_sessions_path %>
</div>

app/views/game_sessions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Game sessions</h1>

<div id="game_sessions">
  <% @game_sessions.each do |game_session| %>
    <%= render game_session %>
    <p>
      <%= link_to "Show this game session", game_session %>
    </p>
  <% end %>
</div>

<%= link_to "New game session", new_game_session_path %>

app/views/game_sessions/new.html.erb
<h1>New game session</h1>

<%= render "form", game_session: @game_session %>

<br>

<div>
  <%= link_to "Back to game sessions", game_sessions_path %>
</div>

app/views/game_sessions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game_session %>

<div>
  <%= link_to "Edit this game session", edit_game_session_path(@game_session) %> |
  <%= link_to "Back to game sessions", game_sessions_path %>

  <%= button_to "Destroy this game session", @game_session, method: :delete %>
</div>

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong>Name:</strong>
    <%= game.name %>
  </p>

</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Games</h1>

<div id="games">
  <% @games.each do |game| %>
    <%= render game %>
    <p>
      <%= link_to "Show this game", game %>
    </p>
  <% end %>
</div>

<%= link_to "New game", new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game %>

<div>
  <%= link_to "Edit this game", edit_game_path(@game) %> |
  <%= link_to "Back to games", games_path %>

  <%= button_to "Destroy this game", @game, method: :delete %>
</div>

app/views/layouts/_header.html.haml
.navbar.navbar-dark.bg-dark
  .container-fluid
    .navbar-brand
      %i.bi.bi-hexagon.logo
      %h3    Viktor Nemeth Andersen

app/views/layouts/_navbar.html.haml
%button{id:"nav-toggle", type:"button", onclick: "toggleNav()"}
  %i.bi.bi-list.open
  %i.bi.bi-X-lg.close

%nav#nav-links-parent{"data-mouse-down-at":"0", "data-prev-percentage": "0"}
  #nav-links.noselect
    .nav-link
      .nav-link-label Hello world!
      = link_to image_tag("arnold-francisca-f77Bh3inUpE-unsplash.jpg", class:"nav-image", draggable: "false"), root_path, class: "nav-link-img"
    .nav-link
      .nav-link-label Hello world!
      = link_to image_tag("arnold-francisca-f77Bh3inUpE-unsplash.jpg", class:"nav-image", draggable: "false"), game_sessions_path, class: "nav-link-img"

app/views/layouts/application.html.haml
%html
  %head
    %title VNemeth
    %meta{ name: "viewport", content:"width=device-width,initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = stylesheet_link_tag "custom", "data-turbo-track": "reload"

    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    = javascript_include_tag "custom", "data-turbo-track": "reload", defer: true

  %body{"data-nav":"false"}
    %main
      = render 'layouts/header'
      = yield
    = render 'layouts/navbar'

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/players/_player.html.erb
<div id="<%= dom_id player %>">
  <p>
    <strong>Name:</strong>
    <%= player.name %>
  </p>

</div>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Show this player", @player %> |
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Players</h1>

<div id="players">
  <% @players.each do |player| %>
    <%= render player %>
    <p>
      <%= link_to "Show this player", player %>
    </p>
  <% end %>
</div>

<%= link_to "New player", new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @player %>

<div>
  <%= link_to "Edit this player", edit_player_path(@player) %> |
  <%= link_to "Back to players", players_path %>

  <%= button_to "Destroy this player", @player, method: :delete %>
</div>

app/views/shared/_errors.html.haml
= pluralize(object.errors.count, "error") + "prohibited this game_session from being saved:"

%ul
  - game_session.errors.each do |error|
    %li = error.full_message